const privileges = {
  admin: {
    "add-new-company": {
      add: true,
    },
    "annual-reports": {
      read: true,
      manage: true,
    },
    "tax-returns": {
      read: true,
      manage: true,
    },
    "budget-and-forcasts": {
      read: true,
      manage: true,
    },
    "board-minutes": {
      read: true,
      manage: true,
    },
    compliance: {
      read: true,
      manage: true,
    },
    sox: {
      read: true,
      manage: true,
    },
    "user-defined": {
      read: true,
      manage: true,
    },
  },
  user: {
    "add-new-company": {
      add: false,
    },
    "annual-reports": {
      read: true,
      manage: false,
    },
    "tax-returns": {
      read: true,
      manage: false,
    },
    "budget-and-forcasts": {
      read: true,
      manage: false,
    },
    "board-minutes": {
      read: true,
      manage: false,
    },
    compliance: {
      read: true,
      manage: false,
    },
    sox: {
      read: true,
      manage: false,
    },
    "user-defined": {
      read: true,
      manage: false,
    },
  },
};

const docsDefaultFields = [
  {
    field: "docType",
    name: "Doc. Type",
    type: "dropdown",
    options: [],
    filter: true,
    sortable: true,
    filterType: "dropdown",
    isRequired: true,
    capitalize: true,
    isActive: true,
    isDefault: true,
    order: 1,
  },
  {
    field: "document",
    name: "Document",
    type: "doc",
    filter: false,
    sortable: false,
    isRequired: true,
    isActive: true,
    isDefault: true,
    order: 2,
  },
  {
    field: "description",
    name: "Description",
    type: "text",
    filter: false,
    sortable: false,
    isRequired: true,
    isActive: true,
    isDefault: true,
    order: 3,
  },
  {
    field: "filedDate",
    name: "Filed Date",
    type: "date",
    filter: true,
    sortable: true,
    filterType: "date",
    isRequired: true,
    isActive: true,
    isDefault: true,
    order: 4,
  },
  {
    field: "dueDate",
    name: "Due Date",
    type: "date",
    filter: true,
    sortable: true,
    filterType: "date",
    isRequired: true,
    isActive: true,
    isDefault: true,
    order: 5,
  },
  {
    field: "frequency",
    name: "Frequency",
    type: "dropdown",
    filter: true,
    sortable: true,
    filterType: "dropdown",
    capitalize: true,
    isRequired: true,
    isActive: true,
    isDefault: true,
    order: 6,
  },
  {
    field: "reminder",
    name: "Reminder",
    type: "text",
    filter: true,
    sortable: true,
    filterType: "text",
    isRequired: true,
    isActive: true,
    isDefault: true,
    order: 7,
  },
];

const defaultFormFields = {
  "company-data": [
    {
      field: "companyName",
      name: "Company Name",
      type: "text",
      filter: true,
      sortable: true,
      filterType: "text",
      expandable: true,
      isActive: true,
      isRequired: true,
      isDefault: true,
      order: 1,
    },
    {
      field: "alias",
      name: "Alias",
      type: "text",
      filter: true,
      sortable: true,
      filterType: "text",
      isActive: true,
      isRequired: true,
      isDefault: true,
      order: 2,
    },
    {
      field: "status",
      name: "Status",
      type: "dropdown",
      filter: true,
      sortable: true,
      filterType: "text",
      isActive: true,
      isRequired: true,
      capitalize: true,
      isDefault: true,
      order: 3,
    },
    {
      field: "companyType",
      name: "Company Type",
      type: "dropdown",
      filter: true,
      sortable: true,
      filterType: "text",
      capitalize: true,
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 4,
    },
    {
      field: "parentCompany",
      name: "State Company",
      type: "dropdown",
      filter: true,
      sortable: true,
      filterType: "text",
      capitalize: false,
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 5,
    },
    {
      field: "business",
      name: "Business",
      type: "text",
      filter: true,
      sortable: true,
      filterType: "text",
      isActive: true,
      isRequired: true,
      isDefault: true,
      order: 6,
    },
    {
      field: "yearEnd",
      name: "Year End",
      type: "date",
      filter: true,
      sortable: true,
      filterType: "date",
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 7,
    },
    {
      field: "currency",
      name: "Currency",
      type: "dropdown",
      filter: true,
      sortable: true,
      filterType: "multiSelect",
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 8,
    },
    {
      field: "previousName",
      name: "Previous Name",
      type: "text",
      filter: true,
      sortable: true,
      filterType: "text",
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 9,
    },
    {
      field: "companyNumber",
      name: "Company No.",
      type: "text",
      filter: true,
      sortable: true,
      filterType: "text",
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 10,
    },
    {
      field: "taxRefNumber",
      name: "Tax Ref. No.",
      type: "text",
      filter: true,
      sortable: true,
      filterType: "text",
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 11,
    },
    {
      field: "vatRefNumber",
      name: "VAT Ref. No.",
      type: "text",
      filter: true,
      sortable: true,
      filterType: "text",
      isRequired: true,
      isActive: true,
      isDefault: true,
      order: 12,
    },
    {
      field: "registeredAddressDetails",
      name: "Registered Address",
      type: "parent",
      childPrefix: "registeredAddress",
      isActive: true,
      isRequired: true,
      isDefault: true,
      children: [
        {
          field: "registeredAddress",
          name: "Address",
          type: "text",
          filter: true,
          sortable: true,
          filterType: "text",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 1,
        },
        {
          field: "registeredAddressCountry",
          name: "Country",
          type: "dropdown",
          filter: true,
          sortable: true,
          filterType: "multiSelect",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 2,
        },
        {
          field: "registeredAddressCity",
          name: "City",
          type: "dropdown",
          filter: true,
          sortable: true,
          filterType: "multiSelect",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 3,
        },
        {
          field: "registeredAddressPostcode",
          name: "Post Code",
          type: "text",
          filter: true,
          sortable: true,
          filterType: "text",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 4,
        },
      ],
      order: 13,
    },
    {
      field: "businessAddressDetails",
      name: "Business Address",
      type: "parent",
      childPrefix: "businessAddress",
      isActive: true,
      isRequired: true,
      isDefault: true,
      children: [
        {
          field: "businessAddress",
          name: "Address",
          type: "text",
          filter: true,
          sortable: true,
          filterType: "text",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 1,
        },
        {
          field: "businessAddressCountry",
          name: "Country",
          type: "dropdown",
          filter: true,
          sortable: true,
          filterType: "multiSelect",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 2,
        },
        {
          field: "businessAddressCity",
          name: "City",
          type: "dropdown",
          filter: true,
          sortable: true,
          filterType: "multiSelect",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 3,
        },
        {
          field: "businessAddressPostcode",
          name: "Post Code",
          type: "text",
          filter: true,
          sortable: true,
          filterType: "text",
          isActive: true,
          isRequired: true,
          isDefault: true,
          order: 4,
        },
      ],
      order: 14,
    },
  ],
  "annual-reports": docsDefaultFields,
  "tax-returns": docsDefaultFields,
  "budget-and-forcasts": docsDefaultFields,
  "board-minutes": docsDefaultFields,
  compliance: docsDefaultFields,
  sox: docsDefaultFields,
  "user-defined": docsDefaultFields,
};

module.exports = { privileges, defaultFormFields };
